version: "3"

services:
  db:
    image: postgres

  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8002
    volumes:
      - .:/code
    ports:
      - "8002:8002"
    depends_on:
      - db